const products = [
  { name: 'Velocity Run', price: 120, type: 'shoes', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=200&q=70' },
  { name: 'Form Tee', price: 42, type: 'apparel', image: 'https://images.unsplash.com/photo-1517832207067-4db24a2ae47c?auto=format&fit=crop&w=200&q=70' },
  { name: 'Day One', price: 95, type: 'shoes', image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=200&q=70' },
  { name: 'Motion Set', price: 68, type: 'apparel', image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=200&q=70' }
];
let bag = [];
const bagEl = document.querySelector('.bag'), backdrop = document.querySelector('.backdrop');
const renderBag = () => { const total = bag.reduce((sum, item) => sum + item.price, 0); document.querySelector('#bag-count').textContent = bag.length; document.querySelector('#bag-total').textContent = `TOTAL $${total}`; document.querySelector('#bag-items').innerHTML = bag.length ? bag.map((item, index) => `<div class="bag-item"><span><b>${item.name}</b><br>$${item.price}</span><button class="remove" data-index="${index}">REMOVE</button></div>`).join('') : '<p>Your bag is empty.</p>'; document.querySelector('#order-link').href = `https://wa.me/15551234567?text=${encodeURIComponent(`Hello! I would like to order: ${bag.map(item => item.name).join(', ')}. Total: $${total}.`)}`; document.querySelectorAll('.remove').forEach(button => button.onclick = () => { bag.splice(button.dataset.index, 1); renderBag(); }); };
const openBag = () => { bagEl.hidden = false; backdrop.hidden = false; }; const closeBag = () => { bagEl.hidden = true; backdrop.hidden = true; };
document.querySelector('#bag-button').onclick = openBag; document.querySelector('#bag-close').onclick = closeBag; backdrop.onclick = closeBag;
document.querySelectorAll('.add').forEach(button => button.onclick = () => { bag.push({ name: button.dataset.product, price: Number(button.dataset.price) }); renderBag(); openBag(); });
document.querySelectorAll('.product-tabs button').forEach(button => button.onclick = () => { document.querySelector('.product-tabs .active').classList.remove('active'); button.classList.add('active'); document.querySelectorAll('.product-grid article').forEach(card => card.classList.toggle('hidden', button.dataset.filter !== 'all' && card.dataset.type !== button.dataset.filter)); });
document.querySelectorAll('[data-carousel]').forEach(button => button.onclick = () => document.querySelector(`#${button.dataset.carousel}`).scrollBy({ left: button.dataset.dir * 320, behavior: 'smooth' }));
const searchPanel = document.querySelector('.search-panel'), searchInput = document.querySelector('#search-input'), searchResults = document.querySelector('#search-results');
document.querySelector('#search-button').onclick = () => { searchPanel.hidden = false; searchInput.focus(); }; document.querySelector('#search-close').onclick = () => searchPanel.hidden = true;
searchInput.oninput = () => { const matches = products.filter(product => product.name.toLowerCase().includes(searchInput.value.toLowerCase())); searchResults.innerHTML = searchInput.value ? matches.map(product => `<div class="search-result"><img src="${product.image}" alt=""><span><b>${product.name}</b><br>$${product.price}</span><button class="quick-add" data-product="${product.name}">ADD</button></div>`).join('') || '<p>No products found.</p>' : ''; document.querySelectorAll('.quick-add').forEach(button => button.onclick = () => { bag.push(products.find(product => product.name === button.dataset.product)); renderBag(); searchPanel.hidden = true; openBag(); }); };
const menu = document.querySelector('.mobile-menu'), nav = document.querySelector('.nav-links'); menu.onclick = () => { const opened = nav.classList.toggle('open'); menu.textContent = opened ? 'CLOSE' : 'MENU'; menu.setAttribute('aria-expanded', opened); };
document.querySelectorAll('.nav-links a').forEach(link => link.onclick = () => { nav.classList.remove('open'); menu.textContent = 'MENU'; menu.setAttribute('aria-expanded', 'false'); });
const dialog = document.querySelector('#member-dialog'); [document.querySelector('#account'), document.querySelector('#account-small'), document.querySelector('#join-button')].forEach(button => button.onclick = () => dialog.showModal()); document.querySelectorAll('.dialog-close').forEach(button => button.onclick = () => dialog.close());
document.querySelector('.notice button').onclick = () => document.querySelector('.notice').remove();
